language: csharp

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

  include:
    - os: linux
      dist: trusty
      dotnet: 2.0.0
      mono: none
    - os: osx
      osx_image: xcode8.2
      dotnet: 2.0.0
      mono: none

branches:
  only:
  - master
script:
  - dotnet test -c Release -f netcoreapp2.0 test/AutoTest.ArgumentNullException.Tests/AutoTest.ArgumentNullException.Tests.csproj
