language: csharp

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

  include:
    - os: linux
      dotnet: 2.1
      mono: none
    - os: osx
      dotnet: 2.1.506
      mono: none

branches:
  only:
  - master

script:
  - dotnet test -c Release -f netcoreapp2.1 test/AutoTest.ArgumentNullException.Tests/AutoTest.ArgumentNullException.Tests.csproj
  - dotnet test -c Release -f netcoreapp2.1 test/AutoTest.ExampleLibrary.Tests/AutoTest.ExampleLibrary.Tests.csproj
