language: csharp

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

  include:
    - os: linux
      dotnet: 2.1
      mono: none
    - os: osx
      dotnet: 2.1.506
      mono: none

branches:
  only:
  - master

script:
  - ./coverage.sh netcoreapp2.1 Release
