# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# Retain the NuGet packages between builds
cache:
  - src\packages -> **\packages.config

# version format
version: 0.8.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# http://blog.appveyor.com/2014/06/04/shallow-clone-for-git-repositories/
shallow_clone: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: y58nAbztko+kSar3VzPnEKhC8W4mA4G0dbtsu4EzpT1G0taRabXjF+v0eggpwcTr

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  project: src\AutoTest.ArgumentNullException.sln
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages

  # MSBuild verbosity level
  verbosity: minimal

# scripts to run before build
before_build: |
  PowerShell .\CiVersion.ps1
  nuget restore src\AutoTest.ArgumentNullException.sln

# to run your custom scripts instead of automatic MSBuild
build_script: |
  cov-build --dir cov-int msbuild src\AutoTest.ArgumentNullException.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build: |
  7z a AutoTest.ArgumentNullException.Coverity.zip cov-int\
  appveyor PushArtifact AutoTest.ArgumentNullException.Coverity.zip -FileName AutoTest.ArgumentNullException.Coverity_%APPVEYOR_BUILD_VERSION%.zip

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: '*.7z'

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script: coverage.cmd

after_test: |
  7z a CoverageResults_%APPVEYOR_BUILD_VERSION%.7z src\Tests\TestResults\
  FOR /r %%F IN (*coveralls.net.exe) DO SET coveralls_exe=%%F
  %coveralls_exe% --opencover src\Tests\TestResults\Test.Coverage.xml

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Slack
  - provider: Slack
    auth_token:
      secure: AkSNuuHmfzAFp2+Oq00NRQFOfrXl4ue08SHx0FC2WTeXSiZv8uVKI3ZBWns7HTcV
    channel: autotest
