//-----------------------------------------------------------------------
// <copyright file="IDiscoverableCollection.cs" company="The glimpse dudes">
//  Shamelessly lifted from Glimpse see: http://getglimpse.com/.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated />

namespace AutoTest.ArgNullEx.Framework
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Defines methods to self discover collection content.
    /// </summary>
    /// <typeparam name="T">Collection item type</typeparam>
    internal interface IDiscoverableCollection<T> : ICollection<T>
    {
        /// <summary>
        /// Gets a value indicating whether [auto discover].
        /// </summary>
        /// <value><see langword="true"/> if [auto discover]; otherwise, <see langword="false"/>.</value>
        /// <remarks>
        /// Indicates whether the system can automatically call Discover()
        /// </remarks>
        bool AutoDiscover { get; }

        /// <summary>
        /// Gets the discovery location.
        /// </summary>
        /// <value>The discovery location.</value>
        string DiscoveryLocation { get; }

        /// <summary>
        /// Ignores the type.
        /// </summary>
        /// <param name="type">The type.</param>
        void IgnoreType(Type type);

        /// <summary>
        /// Discovers this instance. Triggers the loading of content.
        /// </summary>
        void Discover();
    }
}
