version: 2.1

orbs:

  shellcheck: circleci/shellcheck@1

  build:
    jobs:

      run-build:
        parameters:
          image-tag:
            description: The .NET Core SDK image tag to use.
            type: string
          build-config:
            description: The build configuration, either Debug or Release.
            type: string
          framework:
            description: The .NET Core App framework target.
            type: string
        executor:
          name: dotnet-build-executor
          tag: << parameters.image-tag >>
        steps:
          - checkout
          - run:
              name: Test Coverage
              command: ./coverage.sh << parameters.framework >> << parameters.build-config >>
          - store_artifacts:
              path: ./test/TestResults/output/
              destination: /
          - store_test_results:
              path: ./test/TestResults/output/

    executors:

      dotnet-build-executor:
        parameters:
          tag:
            description: The .NET Core SDK image tag to use.
            type: string
        docker:
          - image: mcr.microsoft.com/dotnet/core/sdk:<<parameters.tag>>

workflows:

  "Build All Frameworks":
    jobs:
      - shellcheck/check:
          name: shellcheck
      - build/run-build:
          name: 2.1 Debug Build
          image-tag: "2.1"
          build-config: Debug
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.1 Alpine Debug Build
          image-tag: "2.1-alpine"
          build-config: Debug
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.1 Release Build
          image-tag: "2.1"
          build-config: Release
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.1 Alpine Release Build
          image-tag: "2.1-alpine"
          build-config: Release
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.2 Debug Build
          image-tag: "2.2"
          build-config: Debug
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.2 Alpine Debug Build
          image-tag: "2.2-alpine"
          build-config: Debug
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.2 Release Build
          image-tag: "2.2"
          build-config: Release
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.2 Alpine Release Build
          image-tag: "2.2-alpine"
          build-config: Release
          framework: netcoreapp2.1
